lib/apothecary_web/router.ex
defmodule ApothecaryWeb.Router do
  use ApothecaryWeb, :router

  import ApothecaryWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ApothecaryWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :browser_auth do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ApothecaryWeb.LayoutView, :root}
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ApothecaryWeb do
    pipe_through :browser

    get "/", PotionController, :index
  end

  scope "/", ApothecaryWeb do
    pipe_through [:browser_auth, :require_authenticated_user]

    get "/potion/:id", PotionController, :show
    post "/potion/review/:id", PotionController, :create_review

    get "/users/view/:id", UserController, :show
  end

  # Other scopes may use custom stacks.
  scope "/api", ApothecaryWeb do
    pipe_through :api

    get "/list", PotionController, :api
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: ApothecaryWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", ApothecaryWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ApothecaryWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings/edit_bio", UserSettingsController, :edit_bio
    post "/users/settings/edit_bio", UserSettingsController, :edit_bio

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ApothecaryWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/apothecary/potions.ex
defmodule Apothecary.Potions do
  alias Apothecary.Repo
  alias Apothecary.Potion
  alias Apothecary.Review

  import Ecto.Query

  def get_potion(id) do
    Repo.get(Potion, id)
    |> Repo.preload(:reviews)
  end

  def search_potions(name) do
    q = """
    SELECT p.id, p.name, p.milliliters, p.price, p.secret
    FROM potions as p
    WHERE p.name LIKE '%#{name}%' AND p.secret = false
    """
    {:ok, %{rows: rows}} =
      Ecto.Adapters.SQL.query(Repo, q)
    Enum.map(rows, fn row ->
      [id, name, milliliters, price, secret] = row
      %Potion{id: id, name: name, milliliters: milliliters, price: price, secret: secret}
    end)
  end

  def list_potions() do
    from(p in Potion,
      where: p.secret == false)
    |>
    Repo.all()
  end

  def get_reviews(potion_id) do
    from(r in Review,
      where: r.potion_id == ^potion_id)
    |> Repo.all()
    |> Repo.preload(:user)
  end

  def api() do
    q = from(Potion, order_by: [asc: :id])
    Repo.paginate(q, cursor_fields: [:inserted_at, :id], limit: 2)
  end

  def api(a) do
    q = from(Potion, order_by: [asc: :id])
    Repo.paginate(q, after: a, cursor_fields: [:inserted_at, :id], limit: 2)
  end

  def create_potion(params) do
    %Potion{}
    |> Potion.changeset(params)
    |> Repo.insert()
  end

  def create_review(params) do
    %Review{}
    |> Review.changeset(params)
    |> Repo.insert()
  end
end

lib/apothecary/potions/schema.ex
defmodule Apothecary.Potion do
  use Ecto.Schema
  import Ecto.Changeset

  @derive {Jason.Encoder, only: [:name, :milliliters, :price, :secret]}
  schema "potions" do
    field :name, :string
    field :milliliters, :integer
    field :price, :integer
    field :secret, :boolean

    has_many :reviews, Apothecary.Review

    timestamps()
  end

  def changeset(potion, attrs \\ %{}) do
    potion
    |> cast(attrs, [:name, :milliliters, :price, :secret])
    |> validate_required([:name, :milliliters, :price, :secret])
  end

end

lib/apothecary_web/controllers/potion_controller.ex
defmodule ApothecaryWeb.PotionController do
  use ApothecaryWeb, :controller

  alias Apothecary.Potions
  alias Apothecary.Accounts
  alias Apothecary.Review

  def index(conn, %{"name" => name}) do
    potions = Potions.search_potions(name)
    render(conn, "index.html", potions: potions)
  end

  def index(conn, _params) do
    potions = Potions.list_potions()
    render(conn, "index.html", potions: potions)
  end

  def show(conn, %{"id" => id}) do
    potion = Potions.get_potion(id)
    changeset = Review.changeset(%Review{})
    reviews = Potions.get_reviews(id)
    render(conn, "show.html", potion: potion, reviews: reviews, changeset: changeset)
  end

  def create_review(conn, %{"id" => potion_id, "review" => review_params}) do
    potion = Potions.get_potion(potion_id)
    user = Accounts.get_user_by_email(review_params["email"])
    params =
      review_params
      |> Map.put("user_id", user.id)
      |> Map.put("potion_id", potion_id)
    case Potions.create_review(params) do
      {:ok, _review} ->
        conn
        |> put_flash(:info, "Review created")
        |> redirect(to: Routes.potion_path(conn, :show, potion_id))
      {:error, changeset} ->
        render(conn, "show.html", potion: potion, changeset: changeset)
    end
  end

  def api(conn, %{"after" => a}) do
    %{entries: entries, metadata: m} = Potions.api(a)
    json(conn, %{potions: entries, after: m.after})
  end

  def api(conn, _params) do
    %{entries: entries, metadata: m} = Potions.api()
    json(conn, %{potions: entries, after: m.after})
  end

end

lib/apothecary_web/views/potion_view.ex
defmodule ApothecaryWeb.PotionView do
  use ApothecaryWeb, :view

  def print_cents(c) do
    c / 100
  end
end

lib/apothecary_web/templates/potion/index.html.heex
<div class="flex justify-center pt-4">
  <%= form_for @conn, Routes.potion_path(@conn, :index), [method: :get], fn f -> %>
    <%= text_input f, :name, placeholder: "Potion Name" %>
    <%= submit "Search", class: "bg-purple-800 hover:bg-purple-900 text-white py-2 px-4 rounded shadow" %>
  <% end %>
</div>
<div class="grid grid-cols-1 md:grid-cols-3 grid-cols-2 gap-8 px-10 py-8 max-w-screen-xl">
  <%= for potion <- @potions do %>
    <div class="flex flex-col items-center p-4 shadow border w-56">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-32 h-32">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0112 15a9.065 9.065 0 00-6.23-.693L5 14.5m14.8.8l1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0112 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" />
      </svg>
      <div>
        <div class="text-3xl"><%= potion.name %></div>
        <div class="pt-4"><%= potion.milliliters %> ml</div>
        <div>$<%=print_cents(potion.price) %></div>
        <div class="pt-4">
          <%= link "View", to: Routes.potion_path(@conn, :show, potion.id), class: "bg-purple-800 hover:bg-purple-900 text-white py-2 px-4 rounded shadow" %>
        </div>
      </div>
    </div>
  <% end %>

</div>

lib/apothecary_web/templates/potion/show.html.heex
<div class="py-8 max-w-screen-xl">
  <div class="pb-4">
    <%= link "← Back to All Potions", to: Routes.potion_path(@conn, :index), class: "bg-purple-800 hover:bg-purple-900 text-white py-2 px-4 rounded shadow" %>
  </div>
  <div class="flex flex-col items-center p-4 shadow border w-72">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-32 h-32">
      <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0112 15a9.065 9.065 0 00-6.23-.693L5 14.5m14.8.8l1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0112 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" />
    </svg>
    <div>
      <div class="text-3xl"><%= @potion.name %></div>
      <div class="pt-4"><%= @potion.milliliters %> ml</div>
      <div>$<%=print_cents(@potion.price) %></div>
    </div>
        <div class="pt-4 w-full">
      Customer Reviews:
      <%= for review <- @reviews do %>
        <div class="bg-purple-100 border mt-4 p-1">
          <div class="font-bold text-blue-800 pb-2"><%= link(review.user.email, to: Routes.user_path(@conn, :show, review.user.id)) %></div>
          <div><%= Phoenix.HTML.html_escape(review.body) %></div>
          <div>Rating - <%= review.score %>/5</div>
          <br>
        </div>
      <% end %>
    </div>
    <div class="pt-12 w-full">
      Submit Your Review:
      <%= form_for @changeset, Routes.potion_path(@conn, :create_review, @potion.id), fn f -> %>
        <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p>Error. Please check the errors below.</p>
        </div>
        <% end %>

        <div class="pb-2">
          <%= textarea f, :body, required: true, class: "w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600" %>
          <%= error_tag f, :body%>
        </div>

        5 is best, 1 is worst
        <div class="pt-2 pb-2">
          <%= select f, :score, 1..5, selected: 5 %>
          <%= error_tag f, :score %>
        </div>

        <%= hidden_input f, :email, value: @conn.assigns.current_user.email %>

       <div>
        <%= submit "Submit Review", class: "px-6 py-2 text-white bg-purple-800 border rounded hover:bg-purple-900" %>
      </div>
      <% end %>
    </div>
  </div>
</div>